### ISSUE TITLE
tdk.exceptions.WordNotFoundException Hatası

### ISSUE THREAD

**Issue by muhammedfurkan** [efe/tdk#3]
`result = word.meaning` kısmında raise `WordNotFoundException()  tdk.exceptions.WordNotFoundException` hatası alıyorum.

**Comment by efe** [comment]
Merhaba @muhammedfurkan,

TDK'nın sitesi değiştiği için uygulama şu an çalışmıyor. v2 ile bunu düzelteceğim.
